@startuml
title "Rervation succeeds"

participant Client
participant ReservationSession
participant CarRentalAgency
participant "crcA : CarRentalCompany" as CarRentalCompanyA
participant "crcB : CarRentalCompany" as CarRentalCompanyB


activate Client
activate ReservationSession
activate CarRentalAgency

== confirm the quotes ==

Client -> ReservationSession: confirmQuotes()
ReservationSession -> CarRentalAgency: confirmQuotes([quoteA, quoteB])

CarRentalAgency->CarRentalCompanyA: confirmQuote(quoteA)
CarRentalCompanyA--> CarRentalAgency: reservationA


CarRentalAgency->CarRentalCompanyB: confirmQuote(quoteB)
CarRentalCompanyB--> CarRentalAgency: reservationB

CarRentalAgency-->Client: [reservationA, reservationB]



@enduml
